# Allow local connections
local   all             all                                     peer
host    all             all             127.0.0.1/32            md5

# Allow remote connections with password
host    temizhava       havakalitesi    0.0.0.0/0               md5

