version: '3.8'

services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}  # Custom admin password
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    command: >
      bash -c "echo 'host all all 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf &&
               echo 'listen_addresses=*' >> /var/lib/postgresql/data/postgresql.conf &&
               exec docker-entrypoint.sh postgres"

volumes:
  postgis_data:

